#!/bin/bash

ROOT_DIR="/home/danbooru/danbooru"
SCRIPT_NAME="danbooru.sh"
SCRIPT_FILEPATH="/home/danbooru/danbooru/script/$SCRIPT_NAME"
PID_FILE="/run/danbooru.pid"

. /lib/lsb/init-functions

start() {
    start-stop-daemon --start --quiet --oknodo --background --make-pidfile --pidfile "$PID_FILE" --chuid "danbooru:danbooru" --chdir "$ROOT_DIR" --exec "$SCRIPT_FILEPATH"
}

stop() {
    start-stop-daemon --stop --quiet --oknodo --pidfile "$PID_FILE"
}

case "$1" in 
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status_of_proc -p "$PID_FILE" "$SCRIPT_FILEPATH" "$SCRIPT_NAME"
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
